default:
  before_script:
    - $env:Path = "C:\Python\" + ";" + "C:\Python\Scripts\" + ";" + $env:Path
    - python --version

stages:
  - build
  - release
  - publish

build:
  stage: build
  tags:
    - windows
  script:
    - python -m pip install --upgrade pip
    - echo Uygulama test ediliyor...
    # - python main.py

release:
  stage: release
  tags:
    - windows
  script:
    - python -m pip install -r requirements.txt
    - python -m pip install pyinstaller
    - python -m PyInstaller main.spec
    - Copy-Item "dist\Görsel Veri Etiketleme - FAD.exe" -Destination "."
  artifacts:
    paths:
      - dist/

publish:
  stage: publish
  tags:
    - windows
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release..."
  release:
    name: "Release $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    description: "Bu sürüm $CI_COMMIT_TAG etiketiyle oluşturuldu."
    ref: "$CI_COMMIT_TAG"
    assets:
      links:
        - name: "Windows Uygulaması (.exe)"
          url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/Görsel%20Veri%20Etiketleme%20-%20FAD.exe"
