stages:
  - build
  - release

build:
  stage: build
  tags:
    - windows  # Runner register ederken verdiğin tag
  before_script:
    # 3.10'un path'ini en üste al
    - $env:Path = "C:\Python\" + ";" + "C:\Python\Scripts\" + ";" + $env:Path
    - python --version  # kontrol için
    - python.exe -m pip install --upgrade pip
  script:
    - echo Uygulama test ediliyor...
    # - python main.py  # İstersen basit bir test

release:
  stage: release
  tags:
    - windows
  script:
    - python.exe -m pip install -r requirements.txt
    - python.exe -m pip install pyinstaller
    - python.exe -m PyInstaller main.spec
  artifacts:
    paths:
      - dist/
