default:
  before_script:
    - $env:Path = "C:\Python\" + ";" + "C:\Python\Scripts\" + ";" + $env:Path
    - python --version

stages:
  - build
  - release
  - publish

build:
  stage: build
  tags:
    - windows
  script:
    - python -m pip install --upgrade pip
    - echo Uygulama test ediliyor...
    # - python main.py

release:
  stage: release
  tags:
    - windows
  script:
    - python -m pip install -r requirements.txt
    - python -m pip install pyinstaller
    - python -m PyInstaller main.spec
  artifacts:
    paths:
      - dist/

publish:
  stage: publish
  tags:
    - windows
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      $headers = @{ "PRIVATE-TOKEN" = "$env:GITLAB_API_TOKEN" }

      $body = @{
        name = "Release $env:CI_COMMIT_TAG"
        tag_name = "$env:CI_COMMIT_TAG"
        description = "Bu sürüm $env:CI_COMMIT_TAG etiketiyle oluşturuldu."
        assets = @{
          links = @(
            @{
              name = "Görsel Veri Etiketleme - CATCH"
              url = "$env:CI_PROJECT_URL/-/jobs/$env:CI_JOB_ID/artifacts/download"
            }
          )
        }
      } | ConvertTo-Json -Depth 10

      $apiUrl = "$env:CI_API_V4_URL/projects/$env:CI_PROJECT_ID/releases"

      try {
        Invoke-RestMethod -Uri $apiUrl -Method Post -Headers $headers -Body $body -ContentType "application/json"
        Write-Host "Release created successfully"
      }
      catch {
        Write-Host "Release creation failed!"
        Write-Host "Error: $($_.Exception.Message)"
        throw
      }
