default:
  before_script:
    - $env:Path = "C:\Python\" + ";" + "C:\Python\Scripts\" + ";" + $env:Path
    - python --version

stages:
  - build
  - release
  - publish

build:
  stage: build
  tags:
    - windows
  script:
    - python -m pip install --upgrade pip
    - echo Uygulama test ediliyor...
    # - python main.py

release:
  stage: release
  tags:
    - windows
  script:
    - python -m pip install -r requirements.txt
    - python -m pip install pyinstaller
    - python -m PyInstaller main.spec
    # Save current job ID and git info
    - |
      $env:CI_JOB_ID | Out-File -FilePath "job_id.txt"
      
      # Get previous tag
      $previousTag = git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>$null
      if (-not $previousTag) { $previousTag = "no previous tag" }
      $previousTag | Out-File -FilePath "previous_tag.txt"
      
      # Get commit list
      $commitList = git log --oneline "$previousTag..$env:CI_COMMIT_TAG" --format="%h %s"
      $commitList | Out-File -FilePath "commit_list.txt"
  artifacts:
    paths:
      - dist/
      - job_id.txt
      - previous_tag.txt
      - commit_list.txt

publish:
  stage: publish
  tags:
    - windows
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: release
      artifacts: true

  before_script:
    # release-cli.exe'nin bulunduğu dizini PATH'e ekle
    - |
      $runnerDir = "C:\GitLab-Runner"
      $env:Path = "$runnerDir;" + $env:Path
      Write-Host ">> PATH includes: $runnerDir"

  script:
    - |
      # Artifaktlardan bilgileri oku
      $jobId       = Get-Content job_id.txt
      $previousTag = Get-Content previous_tag.txt
      $commitList  = Get-Content commit_list.txt

      # Burada release-cli'yi doğrudan çağırıyoruz:
      release-cli.exe create `
        --name "Release $env:CI_COMMIT_TAG" `
        --tag-name "$env:CI_COMMIT_TAG" `
        --description "Changes since $previousTag:`n$commitList" `
        --assets-link "name=Application_Executable,url=$CI_PROJECT_URL/-/jobs/$jobId/artifacts/download,link_type=package"

