default:
  before_script:
    - $env:Path = "C:\Python\" + ";" + "C:\Python\Scripts\" + ";" + $env:Path
    - python --version

stages:
  - build
  - release
  - publish

build:
  stage: build
  tags:
    - windows
  script:
    - python -m pip install --upgrade pip
    - echo Uygulama test ediliyor...
    # - python main.py

release:
  stage: release
  tags:
    - windows
  script:
    - python -m pip install -r requirements.txt
    - python -m pip install pyinstaller
    - python -m PyInstaller main.spec
    # Save current job ID and git info
    - |
      $env:CI_JOB_ID | Out-File -FilePath "job_id.txt"
      
      # Get previous tag
      $previousTag = git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>$null
      if (-not $previousTag) { $previousTag = "no previous tag" }
      $previousTag | Out-File -FilePath "previous_tag.txt"
      
      # Get commit list
      $commitList = git log --oneline "$previousTag..$env:CI_COMMIT_TAG" --format="%h %s"
      $commitList | Out-File -FilePath "commit_list.txt"
  artifacts:
    paths:
      - dist/
      - job_id.txt
      - previous_tag.txt
      - commit_list.txt

publish:
  stage: publish
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - windows
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: release
      artifacts: true
  script:
    - |
      $jobId = Get-Content job_id.txt
      $previousTag = Get-Content previous_tag.txt
      $commitList = Get-Content commit_list.txt
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: |
      Release $CI_COMMIT_TAG

      Changes since $previousTag:
      $commitList
    assets:
      links:
        - name: 'Görsel_Veri_Etiketleme_CATCH.exe'
          url: '$CI_PROJECT_URL/-/jobs/$jobId/artifacts/raw/dist/main.exe'
          link_type: 'package'