default:
  before_script:
    - $env:Path = "C:\Python\" + ";" + "C:\Python\Scripts\" + ";" + $env:Path
    - python --version

stages:
  - prepare
  - install
  - build
  - release

update_pip:
  stage: prepare
  tags:
    - windows
  script:
    - python -m pip install --upgrade pip
    - python -m pip install --upgrade setuptools wheel
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - when: never

install_dependencies:
  stage: install
  tags:
    - windows
  script:
    - python -m pip install -r requirements.txt
    - python -m pip install pyinstaller 
  needs: [update_pip]
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - when: never
  needs: [update_pip]


build_application:
  stage: build
  tags:
    - windows
  script:
    - python -m PyInstaller main.spec

    # asset.json oluşturuluyor
    - |
      $json = @{
        name       = "Görsel Veri Etiketleme - CATCH"
        url        = "$env:CI_PROJECT_URL/-/jobs/$env:CI_JOB_ID/artifacts/download"
        filepath   = "/artifact.zip"
        link_type  = "App"
      } | ConvertTo-Json
      $json = $json.Replace('"', '\"')
      Set-Content -Path "asset.json" -Value $json -NoNewline

    # artifact arşivleniyor
    - Compress-Archive -Path dist\* -DestinationPath artifact.zip
  artifacts:
    paths:
      - artifact.zip
      - asset.json
  needs: [install_dependencies]



release_job:
  variables:
    ASSET_URL: "$env:CI_PROJECT_URL/-/jobs/$env:CI_JOB_ID/artifacts/download"
  stage: release
  script:
    - echo "Release $env:CI_COMMIT_TAG"
    - New-Item -ItemType Directory -Force -Path "release_artifacts"
    - Copy-Item -Path "artifact.zip" -Destination "release_artifacts" -Force
    - Copy-Item -Path "asset.json" -Destination "release_artifacts" -Force
    - |
      $link = '[' + (Get-Content asset.json -Raw).Trim() + ']'
      C:\GitLab-Runner\release-cli.exe create `
        --name "Release $env:CI_COMMIT_TAG" `
        --tag-name "$env:CI_COMMIT_TAG" `
        --description "Automated release for $env:CI_COMMIT_TAG" `
        --assets-link "$link"
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - when: never
  tags:
    - windows
  artifacts:
    paths:
      - release_artifacts/
  needs: [build_application]

# build:
#   stage: build
#   tags:
#     - windows
#   script:
#     - python -m pip install --upgrade pip
#     - echo Uygulama test ediliyor...
#     # - python main.py

# release:
#   stage: release
#   tags:
#     - windows
#   script:
#     - python -m pip install -r requirements.txt
#     - python -m pip install pyinstaller
#     - python -m PyInstaller main.spec
#     - |
#       $env:CI_JOB_ID | Out-File -FilePath "job_id.txt"
#       $previousTag = git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>$null
#       if (-not $previousTag) { $previousTag = "no previous tag" }
#       $previousTag | Out-File -FilePath "previous_tag.txt"
#       $commitList = git log --oneline "$previousTag..$env:CI_COMMIT_TAG" --format="%h %s"
#       $commitList | Out-File -FilePath "commit_list.txt"
#   artifacts:
#     paths:
#       - dist/
#       - job_id.txt
#       - previous_tag.txt
#       - commit_list.txt

# publish:
#   stage: publish
#   tags:
#     - windows
#   rules:
#     - if: $CI_COMMIT_TAG
#   needs:
#     - job: release
#       artifacts: true

#   before_script:
#     - |
#       $runnerDir = "C:\GitLab-Runner"
#       $env:Path = "$runnerDir;" + $env:Path
#       Write-Host ">> PATH includes: $runnerDir"

#   script:
#     - |
#       $jobId       = Get-Content job_id.txt
#       $previousTag = Get-Content previous_tag.txt
#       $commitList  = Get-Content commit_list.txt

#       $description = "Changes since $($previousTag):`n$commitList"

#       $assetJson = @{
#         name = "Application_Executable"
#         url = "$env:CI_PROJECT_URL/-/jobs/$jobId/artifacts/download"
#         link_type = "package"
#       } | ConvertTo-Json -Compress

#       & "C:\GitLab-Runner\release-cli.exe" create `
#         --name "Release $env:CI_COMMIT_TAG" `
#         --tag-name "$env:CI_COMMIT_TAG" `
#         --description "$description" `
#         --assets-link $assetJson
