default:
  before_script:
    - $env:Path = "C:\Python\" + ";" + "C:\Python\Scripts\" + ";" + $env:Path
    - python --version

stages:
  - build
  - release
  - publish

build:
  stage: build
  tags:
    - windows
  script:
    - python -m pip install --upgrade pip
    - echo Uygulama test ediliyor...
    # - python main.py

release:
  stage: release
  tags:
    - windows
  script:
    - python -m pip install -r requirements.txt
    - python -m pip install pyinstaller
    - python -m PyInstaller main.spec
    # Save current job ID and git info
    - |
      $env:CI_JOB_ID | Out-File -FilePath "job_id.txt"
      
      # Get previous tag
      $previousTag = git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>$null
      if (-not $previousTag) { $previousTag = "no previous tag" }
      $previousTag | Out-File -FilePath "previous_tag.txt"
      
      # Get commit list
      $commitList = git log --oneline "$previousTag..$env:CI_COMMIT_TAG" --format="%h %s"
      $commitList | Out-File -FilePath "commit_list.txt"
  artifacts:
    paths:
      - dist/
      - job_id.txt
      - previous_tag.txt
      - commit_list.txt

publish:
  stage: publish
  tags:
    - windows
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: release
      artifacts: true

  before_script:
    # 1) release-cli.exe'nin bulunduğu dizini PATH'e ekle
    - |
      $runnerDir = "C:\GitLab-Runner"
      $env:Path = "$runnerDir;" + $env:Path
      Write-Host ">> PATH: $env:Path"

    # 2) CLI'yi bulup sürümünü yazdırarak test et
    - release-cli.exe --version

  script:
    - |
      $jobId       = Get-Content job_id.txt
      $previousTag = Get-Content previous_tag.txt
      $commitList  = Get-Content commit_list.txt

      Write-Host "Release $env:CI_COMMIT_TAG"
      Write-Host "Changes since previous tag ($previousTag):"
      Write-Host $commitList

  release:
    name: "Release $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    description: |
      Release $CI_COMMIT_TAG

      Changes since previous tag ($previousTag):

      $commitList
    assets:
      links:
        - name: "Application_Executable"
          url: "$CI_PROJECT_URL/-/jobs/$jobId/artifacts/download"
          link_type: "package"
