stages:
  - build
  - release

build:
  stage: build
  tags:
    - windows  # Runner register ederken verdiğin tag
  script:
    - echo Uygulama test ediliyor...
    - python main.py  # İstersen basit bir test

release:
  stage: release
  tags:
    - windows
  script:
    - pip install -r requirements.txt
    - pip install pyinstaller
    - python -m PyInstaller main.spec
  artifacts:
    paths:
      - dist/
