stages:
  - build
  - release

build:
  stage: build
  tags:
    - windows  # Runner register ederken verdiğin tag
  before_script:
    - python --version  # kontrol için
    - python -m pip install --upgrade pip
  script:
    - echo Uygulama test ediliyor...
    # - python main.py  # İstersen basit bir test

release:
  stage: release
  tags:
    - windows
  script:
    - python --version  # kontrol için
    - python -m pip install -r requirements.txt
    - python -m pip install pyinstaller
    - python -m PyInstaller main.spec
  artifacts:
    paths:
      - dist/
