# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'label.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(60, 80, 291, 51))
        self.widget.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"}\n"
"QComboBox{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_list = QtWidgets.QComboBox(self.widget)
        self.label_list.setObjectName("label_list")
        self.label_list.addItem("")
        self.label_list.addItem("")
        self.horizontalLayout_2.addWidget(self.label_list)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.view_label = QtWidgets.QPushButton(self.widget_2)
        self.view_label.setMinimumSize(QtCore.QSize(25, 25))
        self.view_label.setMaximumSize(QtCore.QSize(25, 25))
        self.view_label.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/templates/images/view.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/images/templates/images/unview.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.view_label.setIcon(icon)
        self.view_label.setIconSize(QtCore.QSize(22, 22))
        self.view_label.setCheckable(True)
        self.view_label.setObjectName("view_label")
        self.horizontalLayout.addWidget(self.view_label)
        self.delete_label = QtWidgets.QPushButton(self.widget_2)
        self.delete_label.setMinimumSize(QtCore.QSize(25, 25))
        self.delete_label.setMaximumSize(QtCore.QSize(25, 25))
        self.delete_label.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/templates/images/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_label.setIcon(icon1)
        self.delete_label.setIconSize(QtCore.QSize(22, 22))
        self.delete_label.setObjectName("delete_label")
        self.horizontalLayout.addWidget(self.delete_label)
        self.horizontalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_list.setCurrentText(_translate("Form", "asda"))
        self.label_list.setItemText(0, _translate("Form", "asda"))
        self.label_list.setItemText(1, _translate("Form", "asd"))
import rsrc_rc
