# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(718, 518)
        Dialog.setWindowOpacity(1.0)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_main = QtWidgets.QWidget(Dialog)
        self.widget_main.setMaximumSize(QtCore.QSize(700, 500))
        self.widget_main.setStyleSheet("QLabel{\n"
"    color: #EEEEEE;\n"
"}\n"
"QLineEdit{\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    background-color: #1b2027;\n"
"    color: #909398;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid #6086EF;\n"
"    border-radius: 5px;\n"
"    background-color: transparent;\n"
"    color: #6086EF;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #6086EF;\n"
"    color: #EEEEEE;\n"
"}")
        self.widget_main.setObjectName("widget_main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_main)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_left = QtWidgets.QWidget(self.widget_main)
        self.widget_left.setMinimumSize(QtCore.QSize(350, 500))
        self.widget_left.setMaximumSize(QtCore.QSize(350, 500))
        self.widget_left.setStyleSheet("#widget_left{\n"
"    border-top-left-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"    background-color: rgb(34, 40, 49);\n"
"}")
        self.widget_left.setObjectName("widget_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_left)
        self.verticalLayout.setContentsMargins(18, -1, 18, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(-1, 50, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_left)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.lineEdit_username = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_username.setText("")
        self.lineEdit_username.setClearButtonEnabled(True)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout_3.addWidget(self.lineEdit_username)
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setClearButtonEnabled(True)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_3.addWidget(self.lineEdit_password)
        self.pushButton_login = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_login.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout_3.addWidget(self.pushButton_login)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_6 = QtWidgets.QWidget(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setStyleSheet("color: #909398;")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(0, 15, 0, 15)
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line_2 = QtWidgets.QFrame(self.widget_6)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.label_or = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_or.sizePolicy().hasHeightForWidth())
        self.label_or.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_or.setFont(font)
        self.label_or.setObjectName("label_or")
        self.horizontalLayout_5.addWidget(self.label_or)
        self.line = QtWidgets.QFrame(self.widget_6)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_4 = QtWidgets.QWidget(self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 50)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.pushButton_operator_continue = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_operator_continue.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_operator_continue.setFont(font)
        self.pushButton_operator_continue.setObjectName("pushButton_operator_continue")
        self.verticalLayout_4.addWidget(self.pushButton_operator_continue)
        self.verticalLayout.addWidget(self.widget_4)
        self.horizontalLayout_2.addWidget(self.widget_left)
        self.widget_right = QtWidgets.QWidget(self.widget_main)
        self.widget_right.setMinimumSize(QtCore.QSize(350, 500))
        self.widget_right.setMaximumSize(QtCore.QSize(350, 500))
        self.widget_right.setStyleSheet("#widget_right{\n"
"    border-top-right-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"    border-image: url(:/images/templates/images/login-background.jpg);\n"
"    background-color: transparent;\n"
"}")
        self.widget_right.setObjectName("widget_right")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_right)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.widget_right)
        self.widget.setStyleSheet("#widget{\n"
"    border-radius: 15px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 120), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
"#widget:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 80), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setMinimumSize(QtCore.QSize(35, 35))
        self.label_3.setMaximumSize(QtCore.QSize(35, 35))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/images/templates/images/microchip.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #6086EF;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_6.addWidget(self.widget_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3.addWidget(self.widget)
        self.horizontalLayout_2.addWidget(self.widget_right)
        self.horizontalLayout.addWidget(self.widget_main)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Oturum Aç"))
        self.label_2.setText(_translate("Dialog", "Görsel Veri Etiketleme"))
        self.label_4.setText(_translate("Dialog", "Hoşgeldiniz!\n"
"Hesabınıza giriş yapın"))
        self.lineEdit_username.setPlaceholderText(_translate("Dialog", "ismaildrcn"))
        self.lineEdit_password.setPlaceholderText(_translate("Dialog", "Password"))
        self.pushButton_login.setText(_translate("Dialog", "Giriş"))
        self.label_or.setText(_translate("Dialog", "veya"))
        self.label_6.setText(_translate("Dialog", "Operatör olarak devam edin"))
        self.pushButton_operator_continue.setText(_translate("Dialog", "Devam Et"))
        self.label.setText(_translate("Dialog", "CATCH"))
import rsrc_rc
