# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_top = QtWidgets.QWidget(self.centralwidget)
        self.widget_top.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_image_labeling_title = QtWidgets.QLabel(self.widget_top)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_labeling_title.setFont(font)
        self.label_image_labeling_title.setObjectName("label_image_labeling_title")
        self.horizontalLayout_2.addWidget(self.label_image_labeling_title, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.widget_top)
        self.widget_center = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_center.sizePolicy().hasHeightForWidth())
        self.widget_center.setSizePolicy(sizePolicy)
        self.widget_center.setObjectName("widget_center")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_center)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_image_list = QtWidgets.QWidget(self.widget_center)
        self.widget_image_list.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_image_list.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_image_list.setObjectName("widget_image_list")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_image_list)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_image_list_title = QtWidgets.QLabel(self.widget_image_list)
        self.label_image_list_title.setObjectName("label_image_list_title")
        self.verticalLayout_2.addWidget(self.label_image_list_title)
        self.image_list = QtWidgets.QListWidget(self.widget_image_list)
        self.image_list.setObjectName("image_list")
        self.verticalLayout_2.addWidget(self.image_list)
        self.horizontalLayout.addWidget(self.widget_image_list)
        self.widget_labeling_area = QtWidgets.QWidget(self.widget_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_labeling_area.sizePolicy().hasHeightForWidth())
        self.widget_labeling_area.setSizePolicy(sizePolicy)
        self.widget_labeling_area.setObjectName("widget_labeling_area")
        self.horizontalLayout.addWidget(self.widget_labeling_area)
        self.verticalLayout.addWidget(self.widget_center)
        self.widget_bottom = QtWidgets.QWidget(self.centralwidget)
        self.widget_bottom.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_bottom.setObjectName("widget_bottom")
        self.verticalLayout.addWidget(self.widget_bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_image_labeling_title.setText(_translate("MainWindow", "Görsel Etiketleme Aracı"))
        self.label_image_list_title.setText(_translate("MainWindow", "Görseller"))
