# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/templates/images/fad.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: #222831;\n"
"}\n"
"QLabel{\n"
"    color: #EEEEEE;\n"
"}\n"
"QLineEdit{\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_top = QtWidgets.QWidget(self.centralwidget)
        self.widget_top.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_top.setStyleSheet("#widget_top{\n"
"    background-color: #393E46;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    color: #EEEEEE;\n"
"}")
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout_2.setContentsMargins(9, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_topbar_left_actions = QtWidgets.QWidget(self.widget_top)
        self.widget_topbar_left_actions.setObjectName("widget_topbar_left_actions")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_topbar_left_actions)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_actions = QtWidgets.QPushButton(self.widget_topbar_left_actions)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_actions.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/templates/images/fire.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_actions.setIcon(icon1)
        self.pushButton_actions.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_actions.setObjectName("pushButton_actions")
        self.horizontalLayout_4.addWidget(self.pushButton_actions)
        self.horizontalLayout_2.addWidget(self.widget_topbar_left_actions, 0, QtCore.Qt.AlignLeft)
        self.label_image_labeling_title = QtWidgets.QLabel(self.widget_top)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_labeling_title.setFont(font)
        self.label_image_labeling_title.setObjectName("label_image_labeling_title")
        self.horizontalLayout_2.addWidget(self.label_image_labeling_title, 0, QtCore.Qt.AlignHCenter)
        self.widget_topbar_actions = QtWidgets.QWidget(self.widget_top)
        self.widget_topbar_actions.setStyleSheet("")
        self.widget_topbar_actions.setObjectName("widget_topbar_actions")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_topbar_actions)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_hide_window = QtWidgets.QPushButton(self.widget_topbar_actions)
        self.pushButton_hide_window.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_hide_window.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_hide_window.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/templates/images/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_hide_window.setIcon(icon2)
        self.pushButton_hide_window.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_hide_window.setObjectName("pushButton_hide_window")
        self.horizontalLayout.addWidget(self.pushButton_hide_window)
        self.pushButton_fullscreen_window = QtWidgets.QPushButton(self.widget_topbar_actions)
        self.pushButton_fullscreen_window.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_fullscreen_window.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_fullscreen_window.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/templates/images/full-screen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_fullscreen_window.setIcon(icon3)
        self.pushButton_fullscreen_window.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_fullscreen_window.setObjectName("pushButton_fullscreen_window")
        self.horizontalLayout.addWidget(self.pushButton_fullscreen_window)
        self.pushButton_close_window = QtWidgets.QPushButton(self.widget_topbar_actions)
        self.pushButton_close_window.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_close_window.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_close_window.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/templates/images/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close_window.setIcon(icon4)
        self.pushButton_close_window.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_close_window.setObjectName("pushButton_close_window")
        self.horizontalLayout.addWidget(self.pushButton_close_window)
        self.horizontalLayout_2.addWidget(self.widget_topbar_actions, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.widget_top)
        self.pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages.setStyleSheet("#page_labeling, #page_data_importing, #page_init_label{\n"
"    background-color: #222831;\n"
"}")
        self.pages.setObjectName("pages")
        self.page_data_importing = QtWidgets.QWidget()
        self.page_data_importing.setObjectName("page_data_importing")
        self.layout_page_data_importing = QtWidgets.QHBoxLayout(self.page_data_importing)
        self.layout_page_data_importing.setObjectName("layout_page_data_importing")
        self.widget_importing_area = QtWidgets.QWidget(self.page_data_importing)
        self.widget_importing_area.setMinimumSize(QtCore.QSize(450, 300))
        self.widget_importing_area.setMaximumSize(QtCore.QSize(450, 300))
        self.widget_importing_area.setStyleSheet("#widget_importing_area{\n"
"    border-radius:10px;\n"
"    border: 3px solid #00ADB5;\n"
"}")
        self.widget_importing_area.setObjectName("widget_importing_area")
        self.layout_importing_area = QtWidgets.QVBoxLayout(self.widget_importing_area)
        self.layout_importing_area.setContentsMargins(-1, 50, -1, -1)
        self.layout_importing_area.setObjectName("layout_importing_area")
        self.icon_drop_images = QtWidgets.QLabel(self.widget_importing_area)
        self.icon_drop_images.setMinimumSize(QtCore.QSize(60, 60))
        self.icon_drop_images.setMaximumSize(QtCore.QSize(60, 60))
        self.icon_drop_images.setAcceptDrops(True)
        self.icon_drop_images.setText("")
        self.icon_drop_images.setPixmap(QtGui.QPixmap(":/images/templates/images/drop-images.svg"))
        self.icon_drop_images.setScaledContents(True)
        self.icon_drop_images.setObjectName("icon_drop_images")
        self.layout_importing_area.addWidget(self.icon_drop_images, 0, QtCore.Qt.AlignHCenter)
        self.label_drop_images = QtWidgets.QLabel(self.widget_importing_area)
        self.label_drop_images.setAcceptDrops(True)
        self.label_drop_images.setObjectName("label_drop_images")
        self.layout_importing_area.addWidget(self.label_drop_images)
        self.layout_page_data_importing.addWidget(self.widget_importing_area)
        self.pages.addWidget(self.page_data_importing)
        self.page_init_label = QtWidgets.QWidget()
        self.page_init_label.setStyleSheet("#widget_init_label_area, #widget_insert_label_area{\n"
"    border-radius:10px;\n"
"    border: 3px solid #00ADB5;\n"
"}\n"
"QListWidget{\n"
"    background-color: transparent;\n"
"    color: #BBE1FA;\n"
"}\n"
"QPushButton{\n"
"    background-color: #00ADB5;\n"
"    color: #FFFFFF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}")
        self.page_init_label.setObjectName("page_init_label")
        self.layout_page_init_label = QtWidgets.QVBoxLayout(self.page_init_label)
        self.layout_page_init_label.setContentsMargins(-1, -1, -1, 9)
        self.layout_page_init_label.setSpacing(35)
        self.layout_page_init_label.setObjectName("layout_page_init_label")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_page_init_label.addItem(spacerItem)
        self.widget_insert_label_area = QtWidgets.QWidget(self.page_init_label)
        self.widget_insert_label_area.setMinimumSize(QtCore.QSize(450, 150))
        self.widget_insert_label_area.setMaximumSize(QtCore.QSize(450, 150))
        self.widget_insert_label_area.setObjectName("widget_insert_label_area")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_insert_label_area)
        self.verticalLayout_3.setContentsMargins(-1, 25, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.icon_insert_label = QtWidgets.QLabel(self.widget_insert_label_area)
        self.icon_insert_label.setMinimumSize(QtCore.QSize(60, 60))
        self.icon_insert_label.setMaximumSize(QtCore.QSize(60, 60))
        self.icon_insert_label.setText("")
        self.icon_insert_label.setPixmap(QtGui.QPixmap(":/images/templates/images/insert.svg"))
        self.icon_insert_label.setScaledContents(True)
        self.icon_insert_label.setObjectName("icon_insert_label")
        self.verticalLayout_3.addWidget(self.icon_insert_label, 0, QtCore.Qt.AlignHCenter)
        self.label_import_labels = QtWidgets.QLabel(self.widget_insert_label_area)
        self.label_import_labels.setObjectName("label_import_labels")
        self.verticalLayout_3.addWidget(self.label_import_labels)
        self.layout_page_init_label.addWidget(self.widget_insert_label_area, 0, QtCore.Qt.AlignHCenter)
        self.widget_init_label_area = QtWidgets.QWidget(self.page_init_label)
        self.widget_init_label_area.setMinimumSize(QtCore.QSize(450, 300))
        self.widget_init_label_area.setMaximumSize(QtCore.QSize(450, 300))
        self.widget_init_label_area.setObjectName("widget_init_label_area")
        self.layout_init_label_area = QtWidgets.QVBoxLayout(self.widget_init_label_area)
        self.layout_init_label_area.setContentsMargins(20, -1, 20, -1)
        self.layout_init_label_area.setObjectName("layout_init_label_area")
        self.widget_init_label_header = QtWidgets.QWidget(self.widget_init_label_area)
        self.widget_init_label_header.setObjectName("widget_init_label_header")
        self.layout_init_label_header = QtWidgets.QVBoxLayout(self.widget_init_label_header)
        self.layout_init_label_header.setObjectName("layout_init_label_header")
        self.icon_label = QtWidgets.QLabel(self.widget_init_label_header)
        self.icon_label.setMinimumSize(QtCore.QSize(60, 60))
        self.icon_label.setMaximumSize(QtCore.QSize(60, 60))
        self.icon_label.setText("")
        self.icon_label.setPixmap(QtGui.QPixmap(":/images/templates/images/label.svg"))
        self.icon_label.setScaledContents(True)
        self.icon_label.setObjectName("icon_label")
        self.layout_init_label_header.addWidget(self.icon_label, 0, QtCore.Qt.AlignHCenter)
        self.label_create_label = QtWidgets.QLabel(self.widget_init_label_header)
        self.label_create_label.setObjectName("label_create_label")
        self.layout_init_label_header.addWidget(self.label_create_label)
        self.layout_init_label_area.addWidget(self.widget_init_label_header)
        self.listWidget_label_list = QtWidgets.QListWidget(self.widget_init_label_area)
        self.listWidget_label_list.setObjectName("listWidget_label_list")
        self.layout_init_label_area.addWidget(self.listWidget_label_list)
        self.widget_add_label = QtWidgets.QWidget(self.widget_init_label_area)
        self.widget_add_label.setObjectName("widget_add_label")
        self.layout_add_label = QtWidgets.QHBoxLayout(self.widget_add_label)
        self.layout_add_label.setContentsMargins(0, -1, 0, -1)
        self.layout_add_label.setSpacing(20)
        self.layout_add_label.setObjectName("layout_add_label")
        self.lineEdit_add_label = QtWidgets.QLineEdit(self.widget_add_label)
        self.lineEdit_add_label.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_add_label.setObjectName("lineEdit_add_label")
        self.layout_add_label.addWidget(self.lineEdit_add_label)
        self.pushButton_add_label = QtWidgets.QPushButton(self.widget_add_label)
        self.pushButton_add_label.setObjectName("pushButton_add_label")
        self.layout_add_label.addWidget(self.pushButton_add_label)
        self.layout_init_label_area.addWidget(self.widget_add_label)
        self.layout_page_init_label.addWidget(self.widget_init_label_area, 0, QtCore.Qt.AlignHCenter)
        self.widget_init_label_button_area = QtWidgets.QWidget(self.page_init_label)
        self.widget_init_label_button_area.setMinimumSize(QtCore.QSize(450, 50))
        self.widget_init_label_button_area.setMaximumSize(QtCore.QSize(450, 16777215))
        self.widget_init_label_button_area.setStyleSheet("QPushButton{\n"
"    border: 2px solid #00ADB5;\n"
"    background-color: transparent;\n"
"    color: #00ADB5;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #00ADB5;\n"
"    color: #FFFFFF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}")
        self.widget_init_label_button_area.setObjectName("widget_init_label_button_area")
        self.layout_init_label_button_area = QtWidgets.QHBoxLayout(self.widget_init_label_button_area)
        self.layout_init_label_button_area.setContentsMargins(0, 0, 0, 0)
        self.layout_init_label_button_area.setSpacing(50)
        self.layout_init_label_button_area.setObjectName("layout_init_label_button_area")
        self.pushButton_continue_labeling = QtWidgets.QPushButton(self.widget_init_label_button_area)
        self.pushButton_continue_labeling.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_continue_labeling.setObjectName("pushButton_continue_labeling")
        self.layout_init_label_button_area.addWidget(self.pushButton_continue_labeling)
        self.pushButton_export_labels = QtWidgets.QPushButton(self.widget_init_label_button_area)
        self.pushButton_export_labels.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_export_labels.setObjectName("pushButton_export_labels")
        self.layout_init_label_button_area.addWidget(self.pushButton_export_labels)
        self.layout_page_init_label.addWidget(self.widget_init_label_button_area, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_page_init_label.addItem(spacerItem1)
        self.pages.addWidget(self.page_init_label)
        self.page_labeling = QtWidgets.QWidget()
        self.page_labeling.setStyleSheet("QListWidget{\n"
"    background-color: transparent;\n"
"}\n"
"#widget_image_list, #widget_current_label_area{\n"
"    background-color: rgba(57, 62, 70, 128);\n"
"    border-radius: 10px;\n"
"}")
        self.page_labeling.setObjectName("page_labeling")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_labeling)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_image_list = QtWidgets.QWidget(self.page_labeling)
        self.widget_image_list.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_image_list.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_image_list.setStyleSheet("")
        self.widget_image_list.setObjectName("widget_image_list")
        self.layout_image_list = QtWidgets.QVBoxLayout(self.widget_image_list)
        self.layout_image_list.setContentsMargins(9, 12, 9, 12)
        self.layout_image_list.setObjectName("layout_image_list")
        self.label_image_list_title = QtWidgets.QLabel(self.widget_image_list)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_list_title.setFont(font)
        self.label_image_list_title.setObjectName("label_image_list_title")
        self.layout_image_list.addWidget(self.label_image_list_title, 0, QtCore.Qt.AlignHCenter)
        self.image_list = QtWidgets.QListWidget(self.widget_image_list)
        self.image_list.setObjectName("image_list")
        self.layout_image_list.addWidget(self.image_list)
        self.horizontalLayout_3.addWidget(self.widget_image_list)
        self.widget_labeling_area = QtWidgets.QWidget(self.page_labeling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_labeling_area.sizePolicy().hasHeightForWidth())
        self.widget_labeling_area.setSizePolicy(sizePolicy)
        self.widget_labeling_area.setStyleSheet("QGraphicsView{\n"
"    background-color: transparent;\n"
"}")
        self.widget_labeling_area.setObjectName("widget_labeling_area")
        self.layout_labeling_area = QtWidgets.QHBoxLayout(self.widget_labeling_area)
        self.layout_labeling_area.setContentsMargins(0, 0, 0, 0)
        self.layout_labeling_area.setSpacing(0)
        self.layout_labeling_area.setObjectName("layout_labeling_area")
        self.horizontalLayout_3.addWidget(self.widget_labeling_area)
        self.widget_current_label_area = QtWidgets.QWidget(self.page_labeling)
        self.widget_current_label_area.setMinimumSize(QtCore.QSize(250, 200))
        self.widget_current_label_area.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget_current_label_area.setObjectName("widget_current_label_area")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_current_label_area)
        self.verticalLayout_4.setContentsMargins(-1, 12, -1, 12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_current_label_area)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.current_label_list = QtWidgets.QListWidget(self.widget_current_label_area)
        self.current_label_list.setObjectName("current_label_list")
        self.verticalLayout_4.addWidget(self.current_label_list)
        self.horizontalLayout_3.addWidget(self.widget_current_label_area)
        self.pages.addWidget(self.page_labeling)
        self.verticalLayout.addWidget(self.pages)
        self.widget_bottom = QtWidgets.QWidget(self.centralwidget)
        self.widget_bottom.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_bottom.setObjectName("widget_bottom")
        self.verticalLayout.addWidget(self.widget_bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visual Data Labeling"))
        self.pushButton_actions.setText(_translate("MainWindow", "Eylemler"))
        self.label_image_labeling_title.setText(_translate("MainWindow", "Görsel Veri Etiketleme"))
        self.label_drop_images.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resimleri bırakın</span></p><p align=\"center\">veya </p><p align=\"center\"><span style=\" font-weight:600;\">Seçmek için buraya tıklayın</span></p></body></html>"))
        self.label_import_labels.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Etiketleri İçe Aktar</span></p></body></html>"))
        self.label_create_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Etiket Oluştur</span></p></body></html>"))
        self.pushButton_add_label.setText(_translate("MainWindow", "Oluştur"))
        self.pushButton_continue_labeling.setText(_translate("MainWindow", "Devam et"))
        self.pushButton_export_labels.setText(_translate("MainWindow", "Etiketleri Dışa Aktar"))
        self.label_image_list_title.setText(_translate("MainWindow", "Images"))
        self.label.setText(_translate("MainWindow", "Labels"))
import rsrc_rc
