# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/templates/images/fad.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: #222831;\n"
"}\n"
"QLabel{\n"
"    color: #EEEEEE;\n"
"}\n"
"QLineEdit{\n"
"    background-color: #d9eff0;\n"
"    color: #003335;\n"
"    border-radius: 5px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 1px solid #00ADB5;\n"
"}\n"
"\n"
"QHeaderView{\n"
"    background-color: transparent;\n"
"    color: #EEEEEE;\n"
"}\n"
"QHeaderView:section:horizontal{\n"
"    background-color: transparent;\n"
"    border:none;\n"
"    padding-bottom: 5px;\n"
"    border-bottom: 2px solid #00ADB5;\n"
"}\n"
"QHeaderView:section:vertical{\n"
"    background-color: transparent;\n"
"    border:none;\n"
"    padding-bottom: 5px;\n"
"    border-right: 2px solid #00ADB5;\n"
"    }\n"
"QScrollBar:vertical {\n"
"    background: transparent; \n"
"    width: 15px;\n"
"    padding-left: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #596163; \n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background: transparent; \n"
"    height: 15px;\n"
"    padding-top: 5px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #596163; \n"
"    min-width: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {\n"
"    background: #909090;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical, QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    border: none;\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical,\n"
"QScrollBar::up-arrow:horizontal,\n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"    border: none;\n"
"    height: 0px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_top = QtWidgets.QWidget(self.centralwidget)
        self.widget_top.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_top.setStyleSheet("#widget_top{\n"
"    background-color: #393E46;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    color: #EEEEEE;\n"
"}")
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout_2.setContentsMargins(9, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_topbar_left_actions = QtWidgets.QWidget(self.widget_top)
        self.widget_topbar_left_actions.setObjectName("widget_topbar_left_actions")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_topbar_left_actions)
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_exit_project = QtWidgets.QPushButton(self.widget_topbar_left_actions)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_exit_project.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/templates/images/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_exit_project.setIcon(icon1)
        self.pushButton_exit_project.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_exit_project.setObjectName("pushButton_exit_project")
        self.horizontalLayout_4.addWidget(self.pushButton_exit_project)
        self.pushButton_actions = QtWidgets.QPushButton(self.widget_topbar_left_actions)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_actions.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/templates/images/fire.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_actions.setIcon(icon2)
        self.pushButton_actions.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_actions.setObjectName("pushButton_actions")
        self.horizontalLayout_4.addWidget(self.pushButton_actions)
        self.horizontalLayout_2.addWidget(self.widget_topbar_left_actions, 0, QtCore.Qt.AlignLeft)
        self.label_image_labeling_title = QtWidgets.QLabel(self.widget_top)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_labeling_title.setFont(font)
        self.label_image_labeling_title.setObjectName("label_image_labeling_title")
        self.horizontalLayout_2.addWidget(self.label_image_labeling_title, 0, QtCore.Qt.AlignHCenter)
        self.widget_topbar_actions = QtWidgets.QWidget(self.widget_top)
        self.widget_topbar_actions.setStyleSheet("")
        self.widget_topbar_actions.setObjectName("widget_topbar_actions")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_topbar_actions)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_hide_window = QtWidgets.QPushButton(self.widget_topbar_actions)
        self.pushButton_hide_window.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_hide_window.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_hide_window.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/templates/images/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_hide_window.setIcon(icon3)
        self.pushButton_hide_window.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_hide_window.setObjectName("pushButton_hide_window")
        self.horizontalLayout.addWidget(self.pushButton_hide_window)
        self.pushButton_fullscreen_window = QtWidgets.QPushButton(self.widget_topbar_actions)
        self.pushButton_fullscreen_window.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_fullscreen_window.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_fullscreen_window.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/templates/images/full-screen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_fullscreen_window.setIcon(icon4)
        self.pushButton_fullscreen_window.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_fullscreen_window.setObjectName("pushButton_fullscreen_window")
        self.horizontalLayout.addWidget(self.pushButton_fullscreen_window)
        self.pushButton_close_window = QtWidgets.QPushButton(self.widget_topbar_actions)
        self.pushButton_close_window.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_close_window.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_close_window.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/templates/images/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close_window.setIcon(icon5)
        self.pushButton_close_window.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_close_window.setObjectName("pushButton_close_window")
        self.horizontalLayout.addWidget(self.pushButton_close_window)
        self.horizontalLayout_2.addWidget(self.widget_topbar_actions, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.widget_top)
        self.pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages.setStyleSheet("#page_labeling, #page_data_importing, #page_init_label{\n"
"    background-color: #222831;\n"
"}")
        self.pages.setObjectName("pages")
        self.page_data_importing = QtWidgets.QWidget()
        self.page_data_importing.setObjectName("page_data_importing")
        self.layout_page_data_importing = QtWidgets.QHBoxLayout(self.page_data_importing)
        self.layout_page_data_importing.setObjectName("layout_page_data_importing")
        self.widget_importing_area = QtWidgets.QWidget(self.page_data_importing)
        self.widget_importing_area.setMinimumSize(QtCore.QSize(450, 300))
        self.widget_importing_area.setMaximumSize(QtCore.QSize(450, 300))
        self.widget_importing_area.setStyleSheet("#widget_importing_area{\n"
"    border-radius:10px;\n"
"    border: 3px solid #00ADB5;\n"
"}")
        self.widget_importing_area.setObjectName("widget_importing_area")
        self.layout_importing_area = QtWidgets.QVBoxLayout(self.widget_importing_area)
        self.layout_importing_area.setContentsMargins(-1, 50, -1, -1)
        self.layout_importing_area.setObjectName("layout_importing_area")
        self.icon_drop_images = QtWidgets.QLabel(self.widget_importing_area)
        self.icon_drop_images.setMinimumSize(QtCore.QSize(60, 60))
        self.icon_drop_images.setMaximumSize(QtCore.QSize(60, 60))
        self.icon_drop_images.setAcceptDrops(True)
        self.icon_drop_images.setText("")
        self.icon_drop_images.setPixmap(QtGui.QPixmap(":/images/templates/images/drop-images.svg"))
        self.icon_drop_images.setScaledContents(True)
        self.icon_drop_images.setObjectName("icon_drop_images")
        self.layout_importing_area.addWidget(self.icon_drop_images, 0, QtCore.Qt.AlignHCenter)
        self.label_drop_images = QtWidgets.QLabel(self.widget_importing_area)
        self.label_drop_images.setAcceptDrops(True)
        self.label_drop_images.setObjectName("label_drop_images")
        self.layout_importing_area.addWidget(self.label_drop_images)
        self.layout_page_data_importing.addWidget(self.widget_importing_area)
        self.pages.addWidget(self.page_data_importing)
        self.page_init_label = QtWidgets.QWidget()
        self.page_init_label.setStyleSheet("#widget_init_label_area, #widget_insert_label_area{\n"
"    border-radius:10px;\n"
"    border: 3px solid #00ADB5;\n"
"}\n"
"QListWidget{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    color: #EEEEEE;\n"
"}\n"
"QPushButton{\n"
"    background-color: #00ADB5;\n"
"    color: #FFFFFF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}")
        self.page_init_label.setObjectName("page_init_label")
        self.layout_page_init_label = QtWidgets.QVBoxLayout(self.page_init_label)
        self.layout_page_init_label.setContentsMargins(-1, -1, -1, 9)
        self.layout_page_init_label.setSpacing(35)
        self.layout_page_init_label.setObjectName("layout_page_init_label")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_page_init_label.addItem(spacerItem)
        self.widget_insert_label_area = QtWidgets.QWidget(self.page_init_label)
        self.widget_insert_label_area.setMinimumSize(QtCore.QSize(450, 150))
        self.widget_insert_label_area.setMaximumSize(QtCore.QSize(450, 150))
        self.widget_insert_label_area.setObjectName("widget_insert_label_area")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_insert_label_area)
        self.verticalLayout_3.setContentsMargins(-1, 25, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.icon_insert_label = QtWidgets.QLabel(self.widget_insert_label_area)
        self.icon_insert_label.setMinimumSize(QtCore.QSize(60, 60))
        self.icon_insert_label.setMaximumSize(QtCore.QSize(60, 60))
        self.icon_insert_label.setText("")
        self.icon_insert_label.setPixmap(QtGui.QPixmap(":/images/templates/images/insert.svg"))
        self.icon_insert_label.setScaledContents(True)
        self.icon_insert_label.setObjectName("icon_insert_label")
        self.verticalLayout_3.addWidget(self.icon_insert_label, 0, QtCore.Qt.AlignHCenter)
        self.label_import_labels = QtWidgets.QLabel(self.widget_insert_label_area)
        self.label_import_labels.setObjectName("label_import_labels")
        self.verticalLayout_3.addWidget(self.label_import_labels)
        self.layout_page_init_label.addWidget(self.widget_insert_label_area, 0, QtCore.Qt.AlignHCenter)
        self.widget_init_label_area = QtWidgets.QWidget(self.page_init_label)
        self.widget_init_label_area.setMinimumSize(QtCore.QSize(450, 300))
        self.widget_init_label_area.setMaximumSize(QtCore.QSize(450, 300))
        self.widget_init_label_area.setObjectName("widget_init_label_area")
        self.layout_init_label_area = QtWidgets.QVBoxLayout(self.widget_init_label_area)
        self.layout_init_label_area.setContentsMargins(20, -1, 20, -1)
        self.layout_init_label_area.setObjectName("layout_init_label_area")
        self.widget_init_label_header = QtWidgets.QWidget(self.widget_init_label_area)
        self.widget_init_label_header.setObjectName("widget_init_label_header")
        self.layout_init_label_header = QtWidgets.QVBoxLayout(self.widget_init_label_header)
        self.layout_init_label_header.setContentsMargins(-1, 0, -1, -1)
        self.layout_init_label_header.setObjectName("layout_init_label_header")
        self.icon_label = QtWidgets.QLabel(self.widget_init_label_header)
        self.icon_label.setMinimumSize(QtCore.QSize(60, 60))
        self.icon_label.setMaximumSize(QtCore.QSize(60, 60))
        self.icon_label.setText("")
        self.icon_label.setPixmap(QtGui.QPixmap(":/images/templates/images/label.svg"))
        self.icon_label.setScaledContents(True)
        self.icon_label.setObjectName("icon_label")
        self.layout_init_label_header.addWidget(self.icon_label, 0, QtCore.Qt.AlignHCenter)
        self.label_create_label = QtWidgets.QLabel(self.widget_init_label_header)
        self.label_create_label.setObjectName("label_create_label")
        self.layout_init_label_header.addWidget(self.label_create_label)
        self.label_2 = QtWidgets.QLabel(self.widget_init_label_header)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.layout_init_label_header.addWidget(self.label_2)
        self.layout_init_label_area.addWidget(self.widget_init_label_header)
        self.line = QtWidgets.QFrame(self.widget_init_label_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(325, 0))
        self.line.setMaximumSize(QtCore.QSize(325, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layout_init_label_area.addWidget(self.line, 0, QtCore.Qt.AlignHCenter)
        self.listWidget_label_list = QtWidgets.QListWidget(self.widget_init_label_area)
        self.listWidget_label_list.setObjectName("listWidget_label_list")
        self.layout_init_label_area.addWidget(self.listWidget_label_list)
        self.widget_add_label = QtWidgets.QWidget(self.widget_init_label_area)
        self.widget_add_label.setObjectName("widget_add_label")
        self.layout_add_label = QtWidgets.QHBoxLayout(self.widget_add_label)
        self.layout_add_label.setContentsMargins(0, -1, 0, -1)
        self.layout_add_label.setSpacing(20)
        self.layout_add_label.setObjectName("layout_add_label")
        self.lineEdit_add_label = QtWidgets.QLineEdit(self.widget_add_label)
        self.lineEdit_add_label.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_add_label.setText("")
        self.lineEdit_add_label.setClearButtonEnabled(True)
        self.lineEdit_add_label.setObjectName("lineEdit_add_label")
        self.layout_add_label.addWidget(self.lineEdit_add_label)
        self.pushButton_add_label = QtWidgets.QPushButton(self.widget_add_label)
        self.pushButton_add_label.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButton_add_label.setObjectName("pushButton_add_label")
        self.layout_add_label.addWidget(self.pushButton_add_label)
        self.layout_init_label_area.addWidget(self.widget_add_label)
        self.layout_page_init_label.addWidget(self.widget_init_label_area, 0, QtCore.Qt.AlignHCenter)
        self.widget_init_label_button_area = QtWidgets.QWidget(self.page_init_label)
        self.widget_init_label_button_area.setMinimumSize(QtCore.QSize(450, 50))
        self.widget_init_label_button_area.setMaximumSize(QtCore.QSize(450, 16777215))
        self.widget_init_label_button_area.setStyleSheet("QPushButton{\n"
"    border: 2px solid #00ADB5;\n"
"    background-color: transparent;\n"
"    color: #00ADB5;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #00ADB5;\n"
"    color: #FFFFFF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}")
        self.widget_init_label_button_area.setObjectName("widget_init_label_button_area")
        self.layout_init_label_button_area = QtWidgets.QHBoxLayout(self.widget_init_label_button_area)
        self.layout_init_label_button_area.setContentsMargins(0, 0, 0, 0)
        self.layout_init_label_button_area.setSpacing(50)
        self.layout_init_label_button_area.setObjectName("layout_init_label_button_area")
        self.pushButton_continue_labeling = QtWidgets.QPushButton(self.widget_init_label_button_area)
        self.pushButton_continue_labeling.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_continue_labeling.setObjectName("pushButton_continue_labeling")
        self.layout_init_label_button_area.addWidget(self.pushButton_continue_labeling)
        self.pushButton_export_labels = QtWidgets.QPushButton(self.widget_init_label_button_area)
        self.pushButton_export_labels.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_export_labels.setObjectName("pushButton_export_labels")
        self.layout_init_label_button_area.addWidget(self.pushButton_export_labels)
        self.layout_page_init_label.addWidget(self.widget_init_label_button_area, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_page_init_label.addItem(spacerItem1)
        self.pages.addWidget(self.page_init_label)
        self.page_labeling = QtWidgets.QWidget()
        self.page_labeling.setStyleSheet("QListWidget, QTableWidget{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    color: #EEEEEE;\n"
"}\n"
"\n"
"QTableWidget::item:selected, QTableWidget::item:hover{\n"
"    background-color: #272B32;\n"
"    color: #EEEEEE;\n"
"}\n"
"QTableWidget QTableCornerButton::section {\n"
"        background-color: transparent;\n"
"    border-bottom: 2px solid #00ADB5;\n"
"    }\n"
"#widget_image_list, #widget_current_label_area{\n"
"    background-color: rgba(57, 62, 70, 128);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:checked{\n"
"    border:none;\n"
"    background-color: #393E46;\n"
"    border-radius: 3px;\n"
"}")
        self.page_labeling.setObjectName("page_labeling")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_labeling)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.page_labeling)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_image_list = QtWidgets.QWidget(self.widget)
        self.widget_image_list.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_image_list.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_image_list.setStyleSheet("")
        self.widget_image_list.setObjectName("widget_image_list")
        self.layout_image_list = QtWidgets.QVBoxLayout(self.widget_image_list)
        self.layout_image_list.setContentsMargins(9, 12, 9, 9)
        self.layout_image_list.setObjectName("layout_image_list")
        self.label_image_list_title = QtWidgets.QLabel(self.widget_image_list)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_image_list_title.setFont(font)
        self.label_image_list_title.setObjectName("label_image_list_title")
        self.layout_image_list.addWidget(self.label_image_list_title, 0, QtCore.Qt.AlignHCenter)
        self.image_table = QtWidgets.QTableWidget(self.widget_image_list)
        self.image_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.image_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.image_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.image_table.setAlternatingRowColors(False)
        self.image_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.image_table.setShowGrid(False)
        self.image_table.setObjectName("image_table")
        self.image_table.setColumnCount(2)
        self.image_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.image_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.image_table.setHorizontalHeaderItem(1, item)
        self.image_table.horizontalHeader().setVisible(True)
        self.image_table.horizontalHeader().setCascadingSectionResizes(False)
        self.image_table.horizontalHeader().setDefaultSectionSize(50)
        self.image_table.horizontalHeader().setHighlightSections(True)
        self.image_table.horizontalHeader().setMinimumSectionSize(0)
        self.image_table.horizontalHeader().setSortIndicatorShown(False)
        self.image_table.horizontalHeader().setStretchLastSection(True)
        self.image_table.verticalHeader().setVisible(True)
        self.layout_image_list.addWidget(self.image_table)
        self.widget_2 = QtWidgets.QWidget(self.widget_image_list)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_image_title = QtWidgets.QLabel(self.widget_2)
        self.label_image_title.setObjectName("label_image_title")
        self.horizontalLayout_6.addWidget(self.label_image_title)
        self.label_total_image_value = QtWidgets.QLabel(self.widget_2)
        self.label_total_image_value.setText("")
        self.label_total_image_value.setObjectName("label_total_image_value")
        self.horizontalLayout_6.addWidget(self.label_total_image_value)
        self.layout_image_list.addWidget(self.widget_2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addWidget(self.widget_image_list)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_7.setContentsMargins(20, 0, -1, 0)
        self.horizontalLayout_7.setSpacing(15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_zoom_in = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_zoom_in.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_zoom_in.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_zoom_in.setStyleSheet("QPushButton {\n"
"    background-repeat: no-repeat;\n"
"    border-image: url(:/images/templates/images/zoom-in.svg);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/images/templates/images/zoom-in-colorful.svg);\n"
"}")
        self.pushButton_zoom_in.setText("")
        self.pushButton_zoom_in.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_zoom_in.setObjectName("pushButton_zoom_in")
        self.horizontalLayout_7.addWidget(self.pushButton_zoom_in)
        self.pushButton_zoom_out = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_zoom_out.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_zoom_out.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_zoom_out.setStyleSheet("QPushButton {\n"
"    background-repeat: no-repeat;\n"
"    border-image: url(:/images/templates/images/zoom-out.svg);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/images/templates/images/zoom-out-colorful.svg);\n"
"}")
        self.pushButton_zoom_out.setText("")
        self.pushButton_zoom_out.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_zoom_out.setObjectName("pushButton_zoom_out")
        self.horizontalLayout_7.addWidget(self.pushButton_zoom_out)
        self.pushButton_zoom_fit = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_zoom_fit.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_zoom_fit.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_zoom_fit.setStyleSheet("QPushButton {\n"
"    background-repeat: no-repeat;\n"
"    border-image: url(:/images/templates/images/zoom-fit.svg);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/images/templates/images/zoom-fit-colorful.svg);\n"
"}")
        self.pushButton_zoom_fit.setText("")
        self.pushButton_zoom_fit.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_zoom_fit.setObjectName("pushButton_zoom_fit")
        self.horizontalLayout_7.addWidget(self.pushButton_zoom_fit)
        self.line_2 = QtWidgets.QFrame(self.widget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.pushButton_activate_hand = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_activate_hand.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_activate_hand.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_activate_hand.setStyleSheet("QPushButton {\n"
"    background-repeat: no-repeat;\n"
"    border-image: url(:/images/templates/images/hand.svg);\n"
"}\n"
"\n"
"QPushButton:hover, QPushButton:checked {\n"
"    border-image: url(:/images/templates/images/hand-colorful.svg);\n"
"}")
        self.pushButton_activate_hand.setText("")
        self.pushButton_activate_hand.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_activate_hand.setCheckable(True)
        self.pushButton_activate_hand.setObjectName("pushButton_activate_hand")
        self.horizontalLayout_7.addWidget(self.pushButton_activate_hand)
        self.pushButton_activate_crosshair = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_activate_crosshair.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_activate_crosshair.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_activate_crosshair.setStyleSheet("QPushButton {\n"
"    border-image: url(:/images/templates/images/cross-hair.svg);\n"
"}\n"
"\n"
"QPushButton:hover, QPushButton:checked {\n"
"    border-image: url(:/images/templates/images/cross-hair-colorful.svg);\n"
"}")
        self.pushButton_activate_crosshair.setText("")
        self.pushButton_activate_crosshair.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_activate_crosshair.setCheckable(True)
        self.pushButton_activate_crosshair.setChecked(True)
        self.pushButton_activate_crosshair.setObjectName("pushButton_activate_crosshair")
        self.horizontalLayout_7.addWidget(self.pushButton_activate_crosshair)
        self.verticalLayout_5.addWidget(self.widget_3, 0, QtCore.Qt.AlignLeft)
        self.widget_labeling_area = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_labeling_area.sizePolicy().hasHeightForWidth())
        self.widget_labeling_area.setSizePolicy(sizePolicy)
        self.widget_labeling_area.setStyleSheet("QGraphicsView{\n"
"    background-color: transparent;\n"
"}")
        self.widget_labeling_area.setObjectName("widget_labeling_area")
        self.layout_labeling_area = QtWidgets.QVBoxLayout(self.widget_labeling_area)
        self.layout_labeling_area.setContentsMargins(0, 0, 0, 0)
        self.layout_labeling_area.setSpacing(0)
        self.layout_labeling_area.setObjectName("layout_labeling_area")
        self.verticalLayout_5.addWidget(self.widget_labeling_area)
        self.widget_labeling_bottom_area = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_labeling_bottom_area.sizePolicy().hasHeightForWidth())
        self.widget_labeling_bottom_area.setSizePolicy(sizePolicy)
        self.widget_labeling_bottom_area.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_labeling_bottom_area.setStyleSheet("")
        self.widget_labeling_bottom_area.setObjectName("widget_labeling_bottom_area")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_labeling_bottom_area)
        self.horizontalLayout_5.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_previous_image = QtWidgets.QPushButton(self.widget_labeling_bottom_area)
        self.pushButton_previous_image.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_previous_image.setStyleSheet("QPushButton {\n"
"    background-repeat: no-repeat;\n"
"    border-image: url(:/images/templates/images/left.svg);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(57, 62, 70, 64);\n"
"    border-radius:5px;\n"
"    border-image: url(:/images/templates/images/left-colorful.svg);\n"
"}")
        self.pushButton_previous_image.setText("")
        self.pushButton_previous_image.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_previous_image.setObjectName("pushButton_previous_image")
        self.horizontalLayout_5.addWidget(self.pushButton_previous_image)
        self.label_current_image_name = QtWidgets.QLabel(self.widget_labeling_bottom_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_current_image_name.sizePolicy().hasHeightForWidth())
        self.label_current_image_name.setSizePolicy(sizePolicy)
        self.label_current_image_name.setText("")
        self.label_current_image_name.setObjectName("label_current_image_name")
        self.horizontalLayout_5.addWidget(self.label_current_image_name)
        self.pushButton_next_image = QtWidgets.QPushButton(self.widget_labeling_bottom_area)
        self.pushButton_next_image.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_next_image.setStyleSheet("QPushButton {\n"
"    background-repeat: no-repeat;\n"
"    border-image: url(:/images/templates/images/right.svg);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(57, 62, 70, 64);\n"
"    border-radius:5px;\n"
"    border-image: url(:/images/templates/images/right-colorful.svg);\n"
"}")
        self.pushButton_next_image.setText("")
        icon = QtGui.QIcon.fromTheme("dark")
        self.pushButton_next_image.setIcon(icon)
        self.pushButton_next_image.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_next_image.setAutoDefault(False)
        self.pushButton_next_image.setDefault(False)
        self.pushButton_next_image.setFlat(False)
        self.pushButton_next_image.setObjectName("pushButton_next_image")
        self.horizontalLayout_5.addWidget(self.pushButton_next_image)
        self.verticalLayout_5.addWidget(self.widget_labeling_bottom_area, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.widget_current_label_area = QtWidgets.QWidget(self.widget)
        self.widget_current_label_area.setMinimumSize(QtCore.QSize(250, 200))
        self.widget_current_label_area.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget_current_label_area.setObjectName("widget_current_label_area")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_current_label_area)
        self.verticalLayout_4.setContentsMargins(-1, 12, -1, 9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_current_label_area)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.current_label_list = QtWidgets.QListWidget(self.widget_current_label_area)
        self.current_label_list.setStyleSheet("QListWidget::item:selected, QListWidget::item:hover{\n"
"    border:none;\n"
"    background-color: #272B32;\n"
"}")
        self.current_label_list.setObjectName("current_label_list")
        self.verticalLayout_4.addWidget(self.current_label_list)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_total_annotation_title = QtWidgets.QLabel(self.widget_current_label_area)
        self.label_total_annotation_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_total_annotation_title.setObjectName("label_total_annotation_title")
        self.gridLayout.addWidget(self.label_total_annotation_title, 0, 0, 1, 1)
        self.label_total_annotation_value = QtWidgets.QLabel(self.widget_current_label_area)
        self.label_total_annotation_value.setText("")
        self.label_total_annotation_value.setObjectName("label_total_annotation_value")
        self.gridLayout.addWidget(self.label_total_annotation_value, 0, 1, 1, 1)
        self.label_defined_annotation_title = QtWidgets.QLabel(self.widget_current_label_area)
        self.label_defined_annotation_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_defined_annotation_title.setObjectName("label_defined_annotation_title")
        self.gridLayout.addWidget(self.label_defined_annotation_title, 1, 0, 1, 1)
        self.label_defined_annotation_value = QtWidgets.QLabel(self.widget_current_label_area)
        self.label_defined_annotation_value.setText("")
        self.label_defined_annotation_value.setObjectName("label_defined_annotation_value")
        self.gridLayout.addWidget(self.label_defined_annotation_value, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_3.addWidget(self.widget_current_label_area)
        self.verticalLayout_2.addWidget(self.widget)
        self.pages.addWidget(self.page_labeling)
        self.verticalLayout.addWidget(self.pages)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Görsel Veri Etiketleme - FAD"))
        self.pushButton_exit_project.setText(_translate("MainWindow", "Çalışmadan Çık"))
        self.pushButton_actions.setText(_translate("MainWindow", "Eylemler"))
        self.label_image_labeling_title.setText(_translate("MainWindow", "Görsel Veri Etiketleme"))
        self.label_drop_images.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Resimleri bırakın</span></p><p align=\"center\">veya </p><p align=\"center\"><span style=\" font-weight:600;\">Seçmek için buraya tıklayın</span></p></body></html>"))
        self.label_import_labels.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Etiketleri Uygulamaya Aktar</span></p></body></html>"))
        self.label_create_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Etiket Oluştur</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Başlamadan önce, projenizdeki nesnelere atamayı planladığınız etiketlerin bir listesini İngilizce olmak kaydıyla istediğiniz gibi oluşturabilirsiniz.</span></p></body></html>"))
        self.lineEdit_add_label.setPlaceholderText(_translate("MainWindow", "solder-balling"))
        self.pushButton_add_label.setText(_translate("MainWindow", "Oluştur"))
        self.pushButton_continue_labeling.setText(_translate("MainWindow", "Devam et"))
        self.pushButton_export_labels.setText(_translate("MainWindow", "Etiketleri Bilgisayara Aktar"))
        self.label_image_list_title.setText(_translate("MainWindow", "Görseller"))
        self.image_table.setSortingEnabled(False)
        item = self.image_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Durum"))
        item = self.image_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Görsel"))
        self.label_image_title.setText(_translate("MainWindow", "Toplam Görsel:"))
        self.pushButton_zoom_in.setToolTip(_translate("MainWindow", "Yakınlaş"))
        self.pushButton_zoom_out.setToolTip(_translate("MainWindow", "Uzaklaş"))
        self.pushButton_zoom_fit.setToolTip(_translate("MainWindow", "Sığdır"))
        self.pushButton_activate_hand.setToolTip(_translate("MainWindow", "Eller Serbest"))
        self.pushButton_activate_crosshair.setToolTip(_translate("MainWindow", "Seçim Yap"))
        self.label.setText(_translate("MainWindow", "Etiketler"))
        self.label_total_annotation_title.setText(_translate("MainWindow", "Toplam Etiket:"))
        self.label_defined_annotation_title.setText(_translate("MainWindow", "Tanımlanmış Etiket:"))
import rsrc_rc
