# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(518, 335)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_main = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_main.sizePolicy().hasHeightForWidth())
        self.widget_main.setSizePolicy(sizePolicy)
        self.widget_main.setMinimumSize(QtCore.QSize(500, 0))
        self.widget_main.setStyleSheet("#widget_main{\n"
"    border-radius: 10px;\n"
"    background-color: #393E46;    \n"
"}\n"
"QLabel{\n"
"    color: #EEEEEE;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid #00ADB5;\n"
"    color: #FFFFFF;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"#pushButton_ok{\n"
"    background-color: #00ADB5;\n"
"}")
        self.widget_main.setObjectName("widget_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_top_area = QtWidgets.QWidget(self.widget_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_top_area.sizePolicy().hasHeightForWidth())
        self.widget_top_area.setSizePolicy(sizePolicy)
        self.widget_top_area.setObjectName("widget_top_area")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_top_area)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_popup_type = QtWidgets.QWidget(self.widget_top_area)
        self.widget_popup_type.setObjectName("widget_popup_type")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_popup_type)
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.popup_icon = QtWidgets.QLabel(self.widget_popup_type)
        self.popup_icon.setMinimumSize(QtCore.QSize(35, 35))
        self.popup_icon.setMaximumSize(QtCore.QSize(35, 35))
        self.popup_icon.setText("")
        self.popup_icon.setScaledContents(True)
        self.popup_icon.setObjectName("popup_icon")
        self.horizontalLayout_4.addWidget(self.popup_icon)
        self.popup_type = QtWidgets.QLabel(self.widget_popup_type)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.popup_type.setFont(font)
        self.popup_type.setObjectName("popup_type")
        self.horizontalLayout_4.addWidget(self.popup_type)
        self.verticalLayout_2.addWidget(self.widget_popup_type, 0, QtCore.Qt.AlignHCenter)
        self.popup_code = QtWidgets.QLabel(self.widget_top_area)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.popup_code.setFont(font)
        self.popup_code.setAlignment(QtCore.Qt.AlignCenter)
        self.popup_code.setObjectName("popup_code")
        self.verticalLayout_2.addWidget(self.popup_code)
        self.verticalLayout.addWidget(self.widget_top_area)
        self.widget_center_area = QtWidgets.QWidget(self.widget_main)
        self.widget_center_area.setObjectName("widget_center_area")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_center_area)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.popup_message = QtWidgets.QLabel(self.widget_center_area)
        self.popup_message.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.popup_message.setFont(font)
        self.popup_message.setText("")
        self.popup_message.setAlignment(QtCore.Qt.AlignCenter)
        self.popup_message.setWordWrap(True)
        self.popup_message.setObjectName("popup_message")
        self.horizontalLayout_3.addWidget(self.popup_message)
        self.verticalLayout.addWidget(self.widget_center_area)
        self.widget_bottom_area = QtWidgets.QWidget(self.widget_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_bottom_area.sizePolicy().hasHeightForWidth())
        self.widget_bottom_area.setSizePolicy(sizePolicy)
        self.widget_bottom_area.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_bottom_area.setObjectName("widget_bottom_area")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_bottom_area)
        self.horizontalLayout_2.setContentsMargins(-1, 20, 9, 20)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget_bottom_area)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.pushButton_ok = QtWidgets.QPushButton(self.widget_bottom_area)
        self.pushButton_ok.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_2.addWidget(self.pushButton_ok)
        self.verticalLayout.addWidget(self.widget_bottom_area, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.widget_main)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.popup_type.setText(_translate("Dialog", "Warning"))
        self.popup_code.setText(_translate("Dialog", "101"))
        self.pushButton_cancel.setText(_translate("Dialog", "İptal"))
        self.pushButton_ok.setText(_translate("Dialog", "Tamam"))
